apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  namespace: iot
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: changeme-in-production
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-superuser-secret
  namespace: iot
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: changeme-in-production
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: iot
type: Opaque
stringData:
  password: admin
