apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-script
  namespace: iot-gateway
data:
  bridge.py: |
    import paho.mqtt.client as mqtt
    import ssl
    import os
    import json
    import time

    CLOUD_HOST = os.getenv("CLOUD_HOST")
    CLOUD_USER = os.getenv("CLOUD_USER")
    CLOUD_PASS = os.getenv("CLOUD_PASS")
    INTERNAL_HOST = "thingsboard-svc"

    def on_connect(client, userdata, flags, rc):
        if rc == 0:
            print("✅ Connected to HiveMQ Cloud!")
            client.subscribe("v1/gateway/telemetry")
        else:
            print(f"❌ Cloud Connection failed: {rc}")

    def on_message(client, userdata, msg):
        try:
            payload = json.loads(msg.payload.decode())
            # payload is {"Cloud-Simulator-01": [{"values": {"temp": 25}}]}
            for device_name, data_list in payload.items():
                for entry in data_list:
                    values = entry.get("values", entry) # Handle both nested and flat
                    # Forward ONLY the values to make it flat in ThingsBoard
                    print(f"🚀 Flattening & Forwarding for {device_name}: {values}")
                    internal_client.publish(f"v1/gateway/telemetry", json.dumps({device_name: [ {"values": values} ]}))
        except Exception as e:
            print(f"❌ Error: {e}")

    # Internal Client
    internal_client = mqtt.Client()
    internal_client.username_pw_set("BhDbmIyXuWMR0ty9dqOD") # Use the Bridge Gateway Token
    internal_client.connect(INTERNAL_HOST, 1883)
    internal_client.loop_start()

    # Cloud Client
    cloud_client = mqtt.Client()
    cloud_client.username_pw_set(CLOUD_USER, CLOUD_PASS)
    cloud_client.tls_set(cert_reqs=ssl.CERT_REQUIRED)
    cloud_client.on_connect = on_connect
    cloud_client.on_message = on_message

    cloud_client.connect(CLOUD_HOST, 8883)
    cloud_client.loop_forever()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-bridge
  namespace: iot-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-bridge
  template:
    metadata:
      labels:
        app: azure-bridge
    spec:
      containers:
      - name: bridge
        image: python:3.10-slim
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install paho-mqtt==1.6.1
            python -u /app/bridge.py
        env:
        - name: CLOUD_HOST
          value: "c6f88df75120418999bec7e5d6aed17a.s1.eu.hivemq.cloud" 
        - name: CLOUD_USER
          value: "Psdtopicy"
        - name: CLOUD_PASS
          value: "Psdtopicygroup2"
        volumeMounts:
        - name: script-vol
          mountPath: /app
      volumes:
      - name: script-vol
        configMap:
          name: bridge-script