// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: protoc/temperature.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemperatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureRequest) Reset() {
	*x = TemperatureRequest{}
	mi := &file_protoc_temperature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureRequest) ProtoMessage() {}

func (x *TemperatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_temperature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureRequest.ProtoReflect.Descriptor instead.
func (*TemperatureRequest) Descriptor() ([]byte, []int) {
	return file_protoc_temperature_proto_rawDescGZIP(), []int{0}
}

func (x *TemperatureRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *TemperatureRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TemperatureRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *TemperatureRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TemperatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureResponse) Reset() {
	*x = TemperatureResponse{}
	mi := &file_protoc_temperature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureResponse) ProtoMessage() {}

func (x *TemperatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_temperature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureResponse.ProtoReflect.Descriptor instead.
func (*TemperatureResponse) Descriptor() ([]byte, []int) {
	return file_protoc_temperature_proto_rawDescGZIP(), []int{1}
}

func (x *TemperatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTemperaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemperaturesRequest) Reset() {
	*x = GetTemperaturesRequest{}
	mi := &file_protoc_temperature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemperaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemperaturesRequest) ProtoMessage() {}

func (x *GetTemperaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_temperature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemperaturesRequest.ProtoReflect.Descriptor instead.
func (*GetTemperaturesRequest) Descriptor() ([]byte, []int) {
	return file_protoc_temperature_proto_rawDescGZIP(), []int{2}
}

func (x *GetTemperaturesRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *GetTemperaturesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetTemperaturesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetTemperaturesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTemperaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*TemperatureReading  `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemperaturesResponse) Reset() {
	*x = GetTemperaturesResponse{}
	mi := &file_protoc_temperature_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemperaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemperaturesResponse) ProtoMessage() {}

func (x *GetTemperaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_temperature_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemperaturesResponse.ProtoReflect.Descriptor instead.
func (*GetTemperaturesResponse) Descriptor() ([]byte, []int) {
	return file_protoc_temperature_proto_rawDescGZIP(), []int{3}
}

func (x *GetTemperaturesResponse) GetReadings() []*TemperatureReading {
	if x != nil {
		return x.Readings
	}
	return nil
}

type GetLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestRequest) Reset() {
	*x = GetLatestRequest{}
	mi := &file_protoc_temperature_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRequest) ProtoMessage() {}

func (x *GetLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_temperature_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRequest) Descriptor() ([]byte, []int) {
	return file_protoc_temperature_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type TemperatureReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureReading) Reset() {
	*x = TemperatureReading{}
	mi := &file_protoc_temperature_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureReading) ProtoMessage() {}

func (x *TemperatureReading) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_temperature_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureReading.ProtoReflect.Descriptor instead.
func (*TemperatureReading) Descriptor() ([]byte, []int) {
	return file_protoc_temperature_proto_rawDescGZIP(), []int{5}
}

func (x *TemperatureReading) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *TemperatureReading) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TemperatureReading) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *TemperatureReading) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_protoc_temperature_proto protoreflect.FileDescriptor

const file_protoc_temperature_proto_rawDesc = "" +
	"\n" +
	"\x18protoc/temperature.proto\x12\vtemperature\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x12TemperatureRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"/\n" +
	"\x13TemperatureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa6\x01\n" +
	"\x16GetTemperaturesRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"V\n" +
	"\x17GetTemperaturesResponse\x12;\n" +
	"\breadings\x18\x01 \x03(\v2\x1f.temperature.TemperatureReadingR\breadings\"*\n" +
	"\x10GetLatestRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"\x90\x01\n" +
	"\x12TemperatureReading\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xa2\x02\n" +
	"\x12TemperatureService\x12V\n" +
	"\x11RecordTemperature\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\x12\\\n" +
	"\x0fGetTemperatures\x12#.temperature.GetTemperaturesRequest\x1a$.temperature.GetTemperaturesResponse\x12V\n" +
	"\x14GetLatestTemperature\x12\x1d.temperature.GetLatestRequest\x1a\x1f.temperature.TemperatureReadingB-Z+github.com/pangjiade/GCP-ESP/timescaledb/pbb\x06proto3"

var (
	file_protoc_temperature_proto_rawDescOnce sync.Once
	file_protoc_temperature_proto_rawDescData []byte
)

func file_protoc_temperature_proto_rawDescGZIP() []byte {
	file_protoc_temperature_proto_rawDescOnce.Do(func() {
		file_protoc_temperature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_temperature_proto_rawDesc), len(file_protoc_temperature_proto_rawDesc)))
	})
	return file_protoc_temperature_proto_rawDescData
}

var file_protoc_temperature_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protoc_temperature_proto_goTypes = []any{
	(*TemperatureRequest)(nil),      // 0: temperature.TemperatureRequest
	(*TemperatureResponse)(nil),     // 1: temperature.TemperatureResponse
	(*GetTemperaturesRequest)(nil),  // 2: temperature.GetTemperaturesRequest
	(*GetTemperaturesResponse)(nil), // 3: temperature.GetTemperaturesResponse
	(*GetLatestRequest)(nil),        // 4: temperature.GetLatestRequest
	(*TemperatureReading)(nil),      // 5: temperature.TemperatureReading
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_protoc_temperature_proto_depIdxs = []int32{
	6, // 0: temperature.TemperatureRequest.timestamp:type_name -> google.protobuf.Timestamp
	6, // 1: temperature.GetTemperaturesRequest.start:type_name -> google.protobuf.Timestamp
	6, // 2: temperature.GetTemperaturesRequest.end:type_name -> google.protobuf.Timestamp
	5, // 3: temperature.GetTemperaturesResponse.readings:type_name -> temperature.TemperatureReading
	6, // 4: temperature.TemperatureReading.timestamp:type_name -> google.protobuf.Timestamp
	0, // 5: temperature.TemperatureService.RecordTemperature:input_type -> temperature.TemperatureRequest
	2, // 6: temperature.TemperatureService.GetTemperatures:input_type -> temperature.GetTemperaturesRequest
	4, // 7: temperature.TemperatureService.GetLatestTemperature:input_type -> temperature.GetLatestRequest
	1, // 8: temperature.TemperatureService.RecordTemperature:output_type -> temperature.TemperatureResponse
	3, // 9: temperature.TemperatureService.GetTemperatures:output_type -> temperature.GetTemperaturesResponse
	5, // 10: temperature.TemperatureService.GetLatestTemperature:output_type -> temperature.TemperatureReading
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protoc_temperature_proto_init() }
func file_protoc_temperature_proto_init() {
	if File_protoc_temperature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_temperature_proto_rawDesc), len(file_protoc_temperature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_temperature_proto_goTypes,
		DependencyIndexes: file_protoc_temperature_proto_depIdxs,
		MessageInfos:      file_protoc_temperature_proto_msgTypes,
	}.Build()
	File_protoc_temperature_proto = out.File
	file_protoc_temperature_proto_goTypes = nil
	file_protoc_temperature_proto_depIdxs = nil
}
