// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: temperature.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemperatureService_RecordTemperature_FullMethodName    = "/temperature.TemperatureService/RecordTemperature"
	TemperatureService_GetTemperatures_FullMethodName      = "/temperature.TemperatureService/GetTemperatures"
	TemperatureService_GetLatestTemperature_FullMethodName = "/temperature.TemperatureService/GetLatestTemperature"
)

// TemperatureServiceClient is the client API for TemperatureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemperatureServiceClient interface {
	RecordTemperature(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error)
	GetTemperatures(ctx context.Context, in *GetTemperaturesRequest, opts ...grpc.CallOption) (*GetTemperaturesResponse, error)
	GetLatestTemperature(ctx context.Context, in *GetLatestRequest, opts ...grpc.CallOption) (*TemperatureReading, error)
}

type temperatureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemperatureServiceClient(cc grpc.ClientConnInterface) TemperatureServiceClient {
	return &temperatureServiceClient{cc}
}

func (c *temperatureServiceClient) RecordTemperature(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemperatureResponse)
	err := c.cc.Invoke(ctx, TemperatureService_RecordTemperature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temperatureServiceClient) GetTemperatures(ctx context.Context, in *GetTemperaturesRequest, opts ...grpc.CallOption) (*GetTemperaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemperaturesResponse)
	err := c.cc.Invoke(ctx, TemperatureService_GetTemperatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temperatureServiceClient) GetLatestTemperature(ctx context.Context, in *GetLatestRequest, opts ...grpc.CallOption) (*TemperatureReading, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemperatureReading)
	err := c.cc.Invoke(ctx, TemperatureService_GetLatestTemperature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemperatureServiceServer is the server API for TemperatureService service.
// All implementations must embed UnimplementedTemperatureServiceServer
// for forward compatibility.
type TemperatureServiceServer interface {
	RecordTemperature(context.Context, *TemperatureRequest) (*TemperatureResponse, error)
	GetTemperatures(context.Context, *GetTemperaturesRequest) (*GetTemperaturesResponse, error)
	GetLatestTemperature(context.Context, *GetLatestRequest) (*TemperatureReading, error)
	mustEmbedUnimplementedTemperatureServiceServer()
}

// UnimplementedTemperatureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemperatureServiceServer struct{}

func (UnimplementedTemperatureServiceServer) RecordTemperature(context.Context, *TemperatureRequest) (*TemperatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordTemperature not implemented")
}
func (UnimplementedTemperatureServiceServer) GetTemperatures(context.Context, *GetTemperaturesRequest) (*GetTemperaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemperatures not implemented")
}
func (UnimplementedTemperatureServiceServer) GetLatestTemperature(context.Context, *GetLatestRequest) (*TemperatureReading, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestTemperature not implemented")
}
func (UnimplementedTemperatureServiceServer) mustEmbedUnimplementedTemperatureServiceServer() {}
func (UnimplementedTemperatureServiceServer) testEmbeddedByValue()                            {}

// UnsafeTemperatureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemperatureServiceServer will
// result in compilation errors.
type UnsafeTemperatureServiceServer interface {
	mustEmbedUnimplementedTemperatureServiceServer()
}

func RegisterTemperatureServiceServer(s grpc.ServiceRegistrar, srv TemperatureServiceServer) {
	// If the following call pancis, it indicates UnimplementedTemperatureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemperatureService_ServiceDesc, srv)
}

func _TemperatureService_RecordTemperature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureServiceServer).RecordTemperature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureService_RecordTemperature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureServiceServer).RecordTemperature(ctx, req.(*TemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemperatureService_GetTemperatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemperaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureServiceServer).GetTemperatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureService_GetTemperatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureServiceServer).GetTemperatures(ctx, req.(*GetTemperaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemperatureService_GetLatestTemperature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureServiceServer).GetLatestTemperature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureService_GetLatestTemperature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureServiceServer).GetLatestTemperature(ctx, req.(*GetLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemperatureService_ServiceDesc is the grpc.ServiceDesc for TemperatureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemperatureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temperature.TemperatureService",
	HandlerType: (*TemperatureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordTemperature",
			Handler:    _TemperatureService_RecordTemperature_Handler,
		},
		{
			MethodName: "GetTemperatures",
			Handler:    _TemperatureService_GetTemperatures_Handler,
		},
		{
			MethodName: "GetLatestTemperature",
			Handler:    _TemperatureService_GetLatestTemperature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temperature.proto",
}
